language: python
notifications:
  email:
    - thierryschellenbach@gmail.com
    - tbarbugli@gmail.com
python:
  - 3.6
env:
  - REQUIREMENTS=development SETTINGS=facebook_example.settings TESTS=django_facebook
install:
  - pip install pep8 --use-mirrors
  - pip install coverage --use-mirrors
  - pip install unittest2 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - python setup.py install
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 dev_db"
  - pyflakes -x W dev_db
script:
  - pip install -e .
  - pip install django
  - cd dev_db_example
  - manage.py test dev_db
