language: python
notifications:
  email:
    - thierryschellenbach@gmail.com
    - tbarbugli@gmail.com
python:
  - 3.6
env:
  - REQUIREMENTS=development SETTINGS=facebook_example.settings TESTS=django_facebook
install:
  - pip install pep8
  - pip install coverage
  - pip install unittest2
  - pip install pyflakes
  - python setup.py install
before_script:
  - "pep8 --exclude=migrations --ignore=E203,E225,E501,W503 dev_db"
  - pyflakes dev_db
script:
  - pip install -e .
  - pip install django
  - cd dev_db_example
  - python manage.py test dev_db
